"use client";

import * as React from "react";
import Link from "next/link";
import { AlertTriangle, Clock3, Network, Play, RotateCcw, Search, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { CustodyParcelView } from "@/lib/custody/types";

type ParcelSummary = { id: string; externalParcelId: string; currentState: string; currentLocation: string | null; confidenceScore: number; riskLevel: string; dataSource: string; updatedAt: Date | string };

const tone: Record<string, string> = { TRUSTED: "bg-emerald-500/10 text-emerald-700", VERIFIED: "bg-blue-500/10 text-blue-700", REVIEW: "bg-amber-500/10 text-amber-700", CRITICAL: "bg-red-500/10 text-red-700" };
const sourceTone: Record<string, string> = { SYNTHETIC: "border-violet-300 text-violet-700", LIVE: "border-emerald-300 text-emerald-700", FALLBACK: "border-amber-300 text-amber-700", MANUAL: "border-blue-300 text-blue-700" };

function SourceBadge({ value }: { value: string }) { return <Badge variant="outline" className={sourceTone[value] ?? ""}>{value}</Badge>; }

export function CustodyClient({ initial, focusId, disputes = false }: { initial?: ParcelSummary[]; focusId?: string; disputes?: boolean }) {
  const [parcels, setParcels] = React.useState<ParcelSummary[]>(initial ?? []);
  const [selected, setSelected] = React.useState<CustodyParcelView | null>(null);
  const [query, setQuery] = React.useState("");
  const [busy, setBusy] = React.useState(false);
  const [message, setMessage] = React.useState("");

  const loadList = React.useCallback(async () => { const response = await fetch(`/api/custody${query ? `?q=${encodeURIComponent(query)}` : ""}`); if (!response.ok) return; const data = await response.json() as { parcels: ParcelSummary[] }; setParcels(data.parcels); }, [query]);
  const loadParcel = React.useCallback(async (id: string) => { const response = await fetch(`/api/custody/parcels/${encodeURIComponent(id)}`); if (response.ok) setSelected(await response.json() as CustodyParcelView); }, []);
  // These effects synchronize the client view with authenticated API state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  React.useEffect(() => { void loadList(); }, [loadList]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  React.useEffect(() => { if (focusId) void loadParcel(focusId); else if (parcels[0]) void loadParcel(parcels[0].id); }, [focusId, loadParcel, parcels]);

  async function demo(action: "run" | "reset") { setBusy(true); setMessage(""); const response = await fetch(`/api/custody/demo/${action}`, { method: "POST" }); const data = await response.json() as { parcel?: CustodyParcelView; error?: string }; setMessage(response.ok ? action === "run" ? "Synthetic custody journey replayed and recalculated." : "Synthetic custody scenario reset." : data.error ?? "Action failed"); if (data.parcel) setSelected(data.parcel); await loadList(); setBusy(false); }
  async function recalculate() { if (!selected) return; setBusy(true); const response = await fetch("/api/custody/recalculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ parcelId: selected.id }) }); if (response.ok) setSelected(await response.json() as CustodyParcelView); setBusy(false); }
  async function openInvestigation() { if (!selected) return; setBusy(true); const note = window.prompt("Investigation note", "Review the handoff gap and destination hub receiving evidence.") ?? ""; const response = await fetch("/api/custody/investigations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ parcelId: selected.id, note }) }); setMessage(response.ok ? "Investigation opened for Ops review." : "Unable to open investigation."); setBusy(false); }

  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Trust layer · relational graph</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{disputes ? "Custody disputes" : "Chain of Custody"}</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Follow every parcel handoff from OMS to warehouse, vehicle, hub, customer, and return. FLO shows evidence and review windows instead of assigning automatic blame.</p></div><div className="flex gap-2"><Button onClick={() => void demo("run")} disabled={busy}><Play /> Run custody demo</Button><Button variant="outline" onClick={() => void demo("reset")} disabled={busy}><RotateCcw /> Reset</Button></div></div>
    {message && <div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-primary">{message}</div>}
    <div className="grid gap-4 md:grid-cols-4"><Metric label="Parcels tracked" value={parcels.length} icon={<Network />} /><Metric label="Needs review" value={parcels.filter((parcel) => parcel.riskLevel === "REVIEW" || parcel.riskLevel === "CRITICAL").length} icon={<AlertTriangle />} /><Metric label="Synthetic demo" value="Ready" icon={<ShieldCheck />} /><Metric label="Provenance" value="Every event" icon={<Clock3 />} /></div>
    <div className="grid gap-6 lg:grid-cols-[320px_1fr]">
      <Card className="h-fit"><CardHeader><CardTitle>Parcel queue</CardTitle><CardDescription>Search by parcel, barcode, or OMS order.</CardDescription><div className="relative mt-3"><Search className="absolute left-2.5 top-2 h-4 w-4 text-muted-foreground" /><Input className="pl-8" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="BLI-PARCEL-CUST-001" /></div></CardHeader><CardContent className="space-y-2">{parcels.map((parcel) => <button key={parcel.id} type="button" onClick={() => void loadParcel(parcel.id)} className={`w-full rounded-xl border p-3 text-left transition ${selected?.id === parcel.id ? "border-primary bg-primary/5" : "border-border hover:bg-muted/50"}`}><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-medium">{parcel.externalParcelId}</span><Badge className={tone[parcel.riskLevel]}>{parcel.riskLevel}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{parcel.currentState.replaceAll("_", " ")} · {parcel.currentLocation ?? "Location pending"}</p><div className="mt-2 flex items-center justify-between text-[11px] text-muted-foreground"><span>Confidence {Math.round(parcel.confidenceScore)}%</span><SourceBadge value={parcel.dataSource} /></div></button>)}{parcels.length === 0 && <p className="py-6 text-center text-sm text-muted-foreground">No parcels match this search.</p>}</CardContent></Card>
      {selected ? <ParcelDetail parcel={selected} onRecalculate={recalculate} onInvestigation={disputes ? openInvestigation : undefined} busy={busy} /> : <Card><CardContent className="p-8 text-sm text-muted-foreground">Select a parcel to inspect the graph.</CardContent></Card>}
    </div>
  </div>;
}

function Metric({ label, value, icon }: { label: string; value: React.ReactNode; icon: React.ReactNode }) { return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg bg-primary/10 p-2 text-primary">{icon}</div><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div></CardContent></Card>; }

function ParcelDetail({ parcel, onRecalculate, onInvestigation, busy }: { parcel: CustodyParcelView; onRecalculate: () => void; onInvestigation?: () => void; busy: boolean }) {
  const graphActors = parcel.events.flatMap((event) => [event.fromActor, event.toActor]).filter((actor, index, array): actor is NonNullable<typeof actor> => Boolean(actor) && array.findIndex((candidate) => candidate?.id === actor?.id) === index);
  return <div className="space-y-6"><Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><CardTitle>{parcel.externalParcelId}</CardTitle><SourceBadge value={parcel.dataSource} /></div><CardDescription className="mt-1">OMS {parcel.externalOrderId ?? "not linked"} · Return {parcel.externalReturnId ?? "not linked"}</CardDescription></div><div className="flex gap-2"><Button variant="outline" onClick={onRecalculate} disabled={busy}>Recalculate trust</Button>{onInvestigation && <Button onClick={onInvestigation} disabled={busy}>Open investigation</Button>}</div></div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-4"><Summary label="Risk" value={parcel.riskLevel} className={tone[parcel.riskLevel]} /><Summary label="Confidence" value={`${Math.round(parcel.confidenceScore)}%`} /><Summary label="Current state" value={parcel.currentState.replaceAll("_", " ")} /><Summary label="Custodian" value={parcel.currentCustodian?.name ?? "Unassigned"} /></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Custody graph</CardTitle><CardDescription>Actors are nodes; each event is a time-stamped handoff edge.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap items-center gap-2">{graphActors.map((actor, index) => <React.Fragment key={actor.id}><div className="rounded-xl border bg-muted/30 px-3 py-2 text-center"><p className="text-xs font-semibold">{actor.name}</p><p className="text-[10px] text-muted-foreground">{actor.actorType}{actor.hubCode ? ` · ${actor.hubCode}` : ""}</p></div>{index < graphActors.length - 1 && <span className="text-primary">→</span>}</React.Fragment>)}</div></CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><CardTitle>Timeline & provenance</CardTitle><CardDescription>Every observation retains source, validation, and supporting evidence.</CardDescription></CardHeader><CardContent><div className="space-y-4">{parcel.events.map((event) => <div key={event.id} className="relative border-l-2 border-primary/20 pl-4"><div className="absolute -left-[5px] top-1 h-2 w-2 rounded-full bg-primary" /><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{event.eventType.replaceAll("_", " ")}</span><Badge variant="outline">{event.validationStatus}</Badge><SourceBadge value={event.dataSource} /></div><p className="mt-1 text-xs text-muted-foreground">{new Date(event.observedAt).toLocaleString("en-ID")} · {event.hubCode ?? "Location pending"} · {event.toActor?.name ?? "System observation"}</p>{event.evidence.length > 0 && <p className="mt-1 text-xs text-muted-foreground">Evidence: {event.evidence.map((item) => item.evidenceType).join(", ")}</p>}</div>)}</div></CardContent></Card><div className="space-y-6"><Card><CardHeader><CardTitle>Explain this decision</CardTitle><CardDescription>FLO identifies the evidence gap without automatically blaming a person.</CardDescription></CardHeader><CardContent><div className="rounded-xl bg-amber-500/10 p-4 text-sm leading-6">{parcel.responsibilityWindow.statement}</div><div className="mt-4 space-y-2 text-xs"><p><strong>Last known good:</strong> {parcel.responsibilityWindow.lastKnownGood?.label ?? "Not available"} at {parcel.responsibilityWindow.lastKnownGood?.location ?? "unknown"}</p><p><strong>First known bad:</strong> {parcel.responsibilityWindow.firstKnownBad?.label ?? "Not available"} at {parcel.responsibilityWindow.firstKnownBad?.location ?? "unknown"}</p><p><strong>Missing evidence:</strong> {parcel.responsibilityWindow.missingEvidence.join(", ") || "No specific gap"}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Active anomalies</CardTitle></CardHeader><CardContent className="space-y-3">{parcel.anomalies.length === 0 ? <p className="text-sm text-muted-foreground">No active anomalies.</p> : parcel.anomalies.map((anomaly) => <div key={anomaly.id} className="rounded-xl border border-red-200 bg-red-500/5 p-3"><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">{anomaly.kind.replaceAll("CUSTODY_", "").replaceAll("_", " ")}</span><Badge variant="destructive">{anomaly.severity}</Badge></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{anomaly.explanation}</p><p className="mt-2 text-xs font-medium">Next: {anomaly.recommendedAction}</p></div>)}</CardContent></Card></div></div>
    <div className="flex flex-wrap gap-2"><Link href="/custody/disputes" className="text-sm text-primary underline-offset-4 hover:underline">Open dispute workspace →</Link>{parcel.returnCaseId && <Link href={`/returns/${parcel.returnCaseId}`} className="text-sm text-primary underline-offset-4 hover:underline">View linked return →</Link>}</div>
  </div>;
}

function Summary({ label, value, className = "" }: { label: string; value: string; className?: string }) { return <div className={`rounded-xl border p-3 ${className}`}><p className="text-[11px] uppercase tracking-wide opacity-70">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
