"use client";

import { useEffect, useState } from "react";
import { BarChart3, RefreshCw } from "lucide-react";
import { withBasePath } from "@/lib/base-path";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Impact = { generatedAt: string; provenance: string; scenario: { status: string; step: number } | null; operations: Record<string, number>; service: Record<string, number | null>; revisions: Record<string, number | null>; providers: Record<string, number | string | null>; exceptions: Record<string, number>; slaRisk: { activeHighRisk: number; activeCritical: number; predictionsGenerated: number; evaluatedPredictions: number; preventedLateDeliveriesEstimate: number; averageWarningMin: number | null; accuracyPercent: number | null; falsePositiveRatePercent: number | null } };

function value(data: Impact, section: keyof Impact, key: string, suffix = "") { const item = data[section]; return item && typeof item === "object" && key in item ? `${(item as Record<string, number | string | null>)[key] ?? "—"}${suffix}` : "—"; }

function Metric({ title, value: display, detail }: { title: string; value: string; detail?: string }) { return <div className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">{title}</div><div className="mt-1 text-xl font-bold tabular-nums">{display}</div>{detail && <div className="mt-1 text-xs text-muted-foreground">{detail}</div>}</div>; }

export function ImpactDashboardClient() {
  const [data, setData] = useState<Impact | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { const response = await fetch(withBasePath("/api/impact/overview"), { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body?.error ?? "Unable to load impact dashboard"); setData(body); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load impact dashboard"); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  if (!data) return <div className="space-y-4"><h2 className="text-2xl font-bold">Impact dashboard</h2>{error ? <div className="text-sm text-destructive">{error}</div> : <div className="text-sm text-muted-foreground">Loading impact metrics…</div>}</div>;
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-primary" /><h2 className="text-2xl font-bold tracking-tight">Impact dashboard</h2><Badge variant="outline">{data.provenance}</Badge></div><p className="mt-1 text-muted-foreground">Measured operational outcomes from persisted routes, orders, revisions, and provider runs.</p></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "mr-2 h-4 w-4 animate-spin" : "mr-2 h-4 w-4"} />Refresh</Button></div>{error && <div className="rounded-md border border-destructive/30 p-3 text-sm text-destructive">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card><CardHeader><CardTitle className="text-sm">Operations</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><Metric title="Active routes" value={value(data, "operations", "activeRoutes")} /><Metric title="Orders" value={value(data, "operations", "totalOrders")} /><Metric title="Delivered" value={value(data, "operations", "deliveredOrders")} /><Metric title="At risk" value={value(data, "operations", "ordersAtRisk")} /></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Customer promise</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><Metric title="OTIF" value={value(data, "service", "otifPercent", "%")} /><Metric title="On time" value={value(data, "service", "onTimeDeliveries")} /><Metric title="Late" value={value(data, "operations", "lateOrders")} /><Metric title="Protected SLA" value={value(data, "operations", "protectedSlaOrders")} /></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Route and sustainability</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><Metric title="Distance" value={value(data, "operations", "totalDistanceKm", " km")} /><Metric title="Duration" value={value(data, "operations", "averageRouteDurationMin", " min")} /><Metric title="Fuel savings" value={value(data, "operations", "totalFuelSavingsIdr", " IDR")} /><Metric title="CO₂" value={value(data, "operations", "totalEmissionsKg", " kg")} /></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Provider health</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><Metric title="Success rate" value={value(data, "providers", "successRatePercent", "%")} /><Metric title="Runs (24h)" value={value(data, "providers", "ingestionRuns24h")} /><Metric title="Stale feeds" value={value(data, "providers", "staleFeeds")} /><Metric title="Failures" value={value(data, "providers", "failed")} /></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Predictive SLA</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><Metric title="High risk" value={`${data.slaRisk.activeHighRisk}`} /><Metric title="Critical" value={`${data.slaRisk.activeCritical}`} /><Metric title="Early warning" value={data.slaRisk.averageWarningMin == null ? "—" : `${data.slaRisk.averageWarningMin} min`} /><Metric title="Accuracy" value={data.slaRisk.accuracyPercent == null ? "Provisional" : `${data.slaRisk.accuracyPercent}%`} /></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Route intervention results</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric title="Previews" value={value(data, "revisions", "previewed")} /><Metric title="Approved" value={value(data, "revisions", "approved")} /><Metric title="Rejected" value={value(data, "revisions", "rejected")} /><Metric title="Pending" value={value(data, "revisions", "pending")} /><Metric title="Avg duration change" value={value(data, "revisions", "averageDurationChangeMin", " min")} detail="Positive means planned time added." /><Metric title="Affected stops" value={value(data, "revisions", "affectedStops")} /></CardContent></Card>
    <Card><CardHeader><CardTitle>How to interpret this</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Fuel and CO₂ are estimates based on route distance and vehicle type. “Protected SLA” counts approved revisions where the revised stop ETA moved from after the customer promise to within the promise. Predictive SLA accuracy is provisional until delivered orders have prediction history; it compares the last available pre-delivery score with the actual outcome. Synthetic scenario results are labeled and should be presented as a repeatable demonstration, not as historical Blibli performance.</CardContent></Card>
  </div>;
}
