#!/usr/bin/env node
/**
 * FLO laptop install wizard.
 *
 * Usage (from repo root after clone):
 *   npm run install:flo
 *
 * Steps: Node check → choose AI mode → write .env.local → npm ci →
 * prisma migrate → seed → optional ollama pull → print next steps.
 */
import { spawnSync } from "node:child_process";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MIN_NODE_MAJOR = 20;

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, {
    cwd: ROOT,
    stdio: "inherit",
    shell: process.platform === "win32",
    ...opts,
  });
  if (result.status !== 0) {
    throw new Error(`Command failed: ${cmd} ${args.join(" ")}`);
  }
}

function which(bin) {
  const probe = process.platform === "win32" ? "where" : "which";
  const result = spawnSync(probe, [bin], { encoding: "utf8" });
  return result.status === 0;
}

async function ask(rl, question, fallback = "") {
  const hint = fallback ? ` [${fallback}]` : "";
  const answer = (await rl.question(`${question}${hint}: `)).trim();
  return answer || fallback;
}

async function main() {
  console.log("\nFLO — Fab Logistics Operations installer\n");

  const major = Number(process.versions.node.split(".")[0]);
  if (!Number.isFinite(major) || major < MIN_NODE_MAJOR) {
    console.error(
      `Node.js ${MIN_NODE_MAJOR}+ is required (found ${process.versions.node}).`
    );
    process.exit(1);
  }
  console.log(`✓ Node ${process.versions.node}`);

  const rl = createInterface({ input, output });

  console.log("\nChoose default AI mode for .env.local bootstrap:");
  console.log("  1) sovereign — in-process helper only (recommended default)");
  console.log("  2) ollama    — local Ollama at http://127.0.0.1:11434/v1");
  console.log("  3) openai_compatible — cloud / self-hosted OpenAI-compatible API");
  const modeChoice = await ask(rl, "Mode (1/2/3)", "1");

  let mode = "sovereign";
  if (modeChoice === "2") mode = "ollama";
  if (modeChoice === "3") mode = "openai_compatible";

  let aiBaseUrl = "";
  let aiModel = "";
  let aiApiKey = "";
  let pullOllama = false;

  if (mode === "ollama") {
    aiBaseUrl = await ask(
      rl,
      "Ollama OpenAI base URL",
      "http://127.0.0.1:11434/v1"
    );
    aiModel = await ask(rl, "Ollama model", "llama3.2");
    aiApiKey = "ollama";

    if (which("ollama")) {
      console.log("✓ ollama found on PATH");
      const doPull = await ask(rl, `Pull model "${aiModel}" now? (y/N)`, "N");
      pullOllama = /^y(es)?$/i.test(doPull);
    } else {
      console.log(
        "! ollama not found. Install from https://ollama.com/download then run: ollama pull " +
          aiModel
      );
    }
  } else if (mode === "openai_compatible") {
    aiBaseUrl = await ask(
      rl,
      "API base URL (…/v1)",
      "https://api.openai.com/v1"
    );
    aiModel = await ask(rl, "Model id", "gpt-4o-mini");
    aiApiKey = await ask(rl, "API key");
    if (!aiApiKey) {
      console.error("API key is required for openai_compatible mode.");
      process.exit(1);
    }
  }

  const skipSeed = /^y(es)?$/i.test(
    await ask(rl, "Skip database seed? (y/N)", "N")
  );

  rl.close();

  const sessionSecret = randomBytes(32).toString("hex");
  const envLines = [
    "# Generated by npm run install:flo",
    `FLO_SESSION_SECRET=${sessionSecret}`,
    "DATABASE_URL=file:./dev.db",
  ];

  if (mode === "ollama" || mode === "openai_compatible") {
    envLines.push("AI_ALLOW_EXTERNAL=true");
    envLines.push(`AI_API_KEY=${aiApiKey}`);
    envLines.push(`AI_BASE_URL=${aiBaseUrl}`);
    envLines.push(`AI_MODEL=${aiModel}`);
  } else {
    envLines.push("# AI_ALLOW_EXTERNAL=true");
    envLines.push("# AI_API_KEY=");
    envLines.push("# AI_BASE_URL=");
    envLines.push("# AI_MODEL=");
  }

  if (skipSeed) {
    envLines.push("SKIP_SEED=true");
  }

  const envPath = join(ROOT, ".env.local");
  if (existsSync(envPath)) {
    console.log(`\n.env.local already exists — writing ${envPath}.bak and replacing.`);
    writeFileSync(`${envPath}.bak`, readFileSync(envPath));
  }
  writeFileSync(envPath, `${envLines.join("\n")}\n`, "utf8");
  console.log(`✓ Wrote ${envPath}`);

  if (pullOllama) {
    console.log(`\n→ ollama pull ${aiModel}`);
    run("ollama", ["pull", aiModel]);
  }

  console.log("\n→ npm ci");
  run("npm", ["ci"]);

  console.log("\n→ npx prisma migrate deploy");
  run("npx", ["prisma", "migrate", "deploy"]);

  if (!skipSeed) {
    console.log("\n→ npm run db:seed");
    run("npm", ["run", "db:seed"]);
  } else {
    console.log("\nSkipping seed (SKIP_SEED).");
  }

  console.log(`
Done.

Next:
  npm run dev
  open http://localhost:3000/login  (admin@flo.demo / demo1234)
  configure AI at /ai/settings (SQLite overrides this .env.local bootstrap)

Docs: SECURITY.md · README.md
`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
