import type { CustodyEventView } from "./types";

export type AnomalyCandidate = { kind: string; severity: "WATCH" | "HIGH" | "CRITICAL"; reason: string; explanation: string; eventIds: string[]; candidateActorIds: string[]; recommendedAction: string };

export function detectAnomalies(events: CustodyEventView[], input: { expectedHub?: string | null; destinationHub?: string | null; closed?: boolean; serialMismatch?: boolean; conditionConflict?: boolean } = {}): AnomalyCandidate[] {
  const sorted = [...events].sort((a, b) => a.observedAt.localeCompare(b.observedAt));
  const results: AnomalyCandidate[] = [];
  const ids = (event: CustodyEventView) => [event.id];
  for (let index = 0; index < sorted.length; index += 1) {
    const event = sorted[index];
    if (event.validationStatus === "CONFLICTING" && event.hubCode && input.expectedHub && event.hubCode !== input.expectedHub) results.push({ kind: "CUSTODY_WRONG_HUB", severity: "HIGH", reason: `Parcel observed at ${event.hubCode}, expected ${input.expectedHub}.`, explanation: "The scan is valid evidence of an observation, but the location conflicts with the expected custody route.", eventIds: ids(event), candidateActorIds: event.toActor ? [event.toActor.id] : [], recommendedAction: "Verify route assignment and receiving records at both hubs." });
    if (index > 0 && sorted[index - 1].eventType === event.eventType && sorted[index - 1].toActor?.id === event.toActor?.id) results.push({ kind: "CUSTODY_DUPLICATE_SCAN", severity: "WATCH", reason: `Repeated ${event.eventType.toLowerCase().replaceAll("_", " ")} event.`, explanation: "Two equivalent observations were received for the same custody stage.", eventIds: [sorted[index - 1].id, event.id], candidateActorIds: event.toActor ? [event.toActor.id] : [], recommendedAction: "Keep the first event and review the duplicate device or integration delivery." });
    if (index > 0 && new Date(event.observedAt) < new Date(sorted[index - 1].observedAt)) results.push({ kind: "CUSTODY_TIME_CONFLICT", severity: "HIGH", reason: "Event timestamp precedes the previous custody event.", explanation: "The event ordering cannot be trusted without checking device clock and source timestamps.", eventIds: [sorted[index - 1].id, event.id], candidateActorIds: [], recommendedAction: "Compare source receipt time with the device timestamp." });
  }
  const hasRelease = sorted.some((event) => event.eventType === "WAREHOUSE_RELEASE" || event.eventType === "PARCEL_SEALED");
  const hasAcceptance = sorted.some((event) => event.eventType === "DRIVER_ACCEPTED" || event.eventType === "VEHICLE_LOADED");
  if (hasRelease && !hasAcceptance) results.push({ kind: "CUSTODY_MISSING_HANDOFF", severity: "HIGH", reason: "Warehouse released the parcel but no driver or vehicle acceptance was recorded.", explanation: "The parcel left the last verified warehouse state without a matching receiving handoff.", eventIds: sorted.filter((event) => event.eventType === "WAREHOUSE_RELEASE" || event.eventType === "PARCEL_SEALED").map((event) => event.id), candidateActorIds: [], recommendedAction: "Verify physical handoff, scan-device logs, and vehicle loading records." });
  const arrived = sorted.find((event) => event.eventType === "HUB_ARRIVAL");
  if (arrived && !sorted.some((event) => event.eventType === "HUB_RECEIVED")) results.push({ kind: "CUSTODY_MISSING_HANDOFF", severity: "HIGH", reason: "Vehicle arrival exists but the destination hub receiving handoff is missing.", explanation: "FLO can prove arrival evidence, but cannot prove that the hub accepted custody into its receiving lane.", eventIds: [arrived.id], candidateActorIds: arrived.toActor ? [arrived.toActor.id] : [], recommendedAction: "Review hub receiving lane records, dock camera evidence, and the next scan." });
  if (input.serialMismatch) results.push({ kind: "CUSTODY_SERIAL_MISMATCH", severity: "CRITICAL", reason: "Observed serial number conflicts with the OMS/WMS identity.", explanation: "Parcel identity cannot be trusted until the item and order are reconciled.", eventIds: sorted.map((event) => event.id), candidateActorIds: [], recommendedAction: "Hold the parcel and request a warehouse identity check." });
  if (input.conditionConflict) results.push({ kind: "CUSTODY_CONDITION_CONFLICT", severity: "HIGH", reason: "Outbound sealed evidence conflicts with inbound damaged evidence.", explanation: "The condition changed between two verified observations; the responsible segment requires review.", eventIds: sorted.map((event) => event.id), candidateActorIds: [], recommendedAction: "Review the responsibility window and handling evidence." });
  if (input.closed && sorted.some((event) => event.eventType === "DELIVERED" && new Date(event.observedAt) < new Date(sorted[sorted.length - 1].observedAt))) results.push({ kind: "CUSTODY_DUPLICATE_SCAN", severity: "HIGH", reason: "Parcel was observed after delivery closure.", explanation: "A post-closure event may be a replay or an unrecorded return movement.", eventIds: [sorted[sorted.length - 1].id], candidateActorIds: [], recommendedAction: "Confirm whether this is a return event or a replayed scan." });
  return results;
}
